mutable flag for txt livedns_records
go-gandi/terraform-provider-gandi pull request #111
Opened 2022-04-05 17:07 UTC by adriamanu

The purpose of this PR is to add a **mutable** flag on **livedns_records** to be able to manipulate records that are susceptible of being already existant / modified aside Terraform.
With this pull request, gandi provider will only touch records managed by Terraform by doing **PUT** crud operation from gandi api in order to **update/edit** the list of records.
[This is the related issue](https://github.com/go-gandi/terraform-provider-gandi/issues/106)

2022-04-07 07:04 UTC, nlewo requested changes
Thanks for this nice contribution!

When this first batch of reviews is addressed, I will add an acceptance test (unfortunately, you can't currently do it because it relies on domain that has to exist in the Gandi Sandbox).

2022-04-07 07:04 UTC, nlewo commented on gandi/resource_livedns_record.go
> +func containsRecord(recordsList []string, recordToFind string) int {
Could you return a tuple such as `(index int, exist bool)` instead of encoding a non existing record with `-1`?

2022-04-07 07:04 UTC, nlewo commented on gandi/resource_livedns_record.go
> +func containsRecord(recordsList []string, recordToFind string) int {
Could you return a tuple such as `(index int, exist bool)` instead of encoding a non existing record with `-1`?

2022-04-07 07:04 UTC, nlewo commented on gandi/resource_livedns_record.go
> +				index := containsRecord(values, "\""+v.(string)+"\"")
```suggestion
				index := containsRecord(values, "\""+v.(string)+"\"")
```
```suggestion
				indexm exists := containsRecord(values, "\""+v.(string)+"\"")
```

2022-04-07 07:04 UTC, nlewo commented on gandi/resource_livedns_record.go
> +				index := containsRecord(values, "\""+v.(string)+"\"")
```suggestion
				index, exists := containsRecord(values, "\""+v.(string)+"\"")
```
```suggestion
				index := containsRecord(values, "\""+v.(string)+"\"")
```

2022-04-07 07:04 UTC, nlewo commented on gandi/resource_livedns_record.go
> +				index := containsRecord(values, "\""+v.(string)+"\"")
```suggestion
				index, exists := containsRecord(values, "\""+v.(string)+"\"")
```

2022-05-22 14:03 UTC, adriamanu commented
Hello @nlewo , i hope you are doing well.
i updated pr according to your requested changes (some logic modification / unit tests / generate documentation).
Apologies for the delayed update.
Took me some time to test it again and check for edge cases.
Have a good day !

2022-05-25 16:21 UTC, nlewo commented
I did some manual tests are write an acceptance test in #117.

Everything looks fine :tada: 

@adriamanu Once this PR is merged, i will rebase #117.

2022-05-26 14:27 UTC, adriamanu commented
I'm glad to read that !
@nlewo rebase has been done so that there is only 1 commit to merge (typos have been fixed during the rebasing process).

2022-05-30 08:16 UTC, merged

2022-05-30 08:16 UTC, nlewo commented
@adriamanu Thank you!

2022-05-30 08:23 UTC, adriamanu commented
Thank you for the support, keep up the good work @nlewo  🙏🏼 !